### ISSUE TITLE
INSTALL_FAILED_INVALID_APK on sample apk

### ISSUE THREAD

**Issue by John61590** [rnevet/WCViewPager#11]
I tried to install the sample app, but get this message on adb.

**Comment by rnevet** [comment]
I've just tested and had no problem downloading and installing the apk.

https://github.com/rnevet/WCViewPager/raw/master/app/wcviewpager-sample.apk

**Comment by John61590** [comment]
adb install wcviewpager-sample.apk
	pkg: /data/local/tmp/wcviewpager-sample.apk
Failure [INSTALL_FAILED_INVALID_APK]

**Comment by rnevet** [comment]
Please try downloading the APK again, I cannot help with ENV specific issues.

**Comment by John61590** [comment]
Ah I found out it was something weird where Firefox was downloading 0 bytes because the apk was "suspicious."
