### ISSUE TITLE
first tab height issue 

### ISSUE THREAD

**Issue by d7coders** [rnevet/WCViewPager#2]
the first tab not expands but when change the tab and select the first one again it's expands

**Comment by rnevet** [comment]
@d7coders can you add some code sample that will help reproduce this? maybe fork the project and change the example?

**Comment by John61590** [comment]
This happened to me too.

**Comment by rnevet** [comment]
@John61590 and can you add some code sample that will help reproduce this? maybe fork the project and change the example?
