### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by luizfp** [rnevet/WCViewPager#4]
I was trying to prevent the user to swipe to right (only left) in view pager and found this solution: [http://stackoverflow.com/a/21603398/4744158](http://stackoverflow.com/a/21603398/4744158).

This solution above works fine with the native ViewPager, but if I use WCViewPager I get the exception:

`java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!` 

This happens if I call `notifyDataSetChanged()` from my adapter.

The problem is with `PagerAdapterWrapper`. If I change the method `notifyDataSetChanged()` for this:

``` java
@Override
public void notifyDataSetChanged() {
    super.notifyDataSetChanged(); // new line
    innerAdapter.notifyDataSetChanged();
}
```

The crash doesnt happen anymore, but, unfortunately, the resize doesnt work either. :/

**Comment by rnevet** [comment]
Without seeing your implementation it's really hard to say, could you fork the repository and modify the sample app to reproduce the issue?

**Comment by luizfp** [comment]
Off course! When I finish I let you know.

**Comment by luizfp** [comment]
It's done: [https://github.com/luizfp/WCViewPager](https://github.com/luizfp/WCViewPager)

It took me a lot of time because I left the code quite the same of my app but the problem seems to not happen. But, after I updated the support library and all the other stuff the problem was there. I have not tested yet, but probably the same problem will happen if you add some content to the adapter dynamically and call `notifyDataSetChanged()`.

If you look at the code now you will see that when you click in one adapter item I do this:

``` java
    @Override
    public void onClick(View view) {
        mListener.onClickAdapterItem();
    }
```

This tells the activity that an item was clicked and, in response, the activity calls this method back in the adapter:

``` java
 @Override
    public boolean enableNext() {
        if (count >= images.size())
            return false;

        count++;
        notifyDataSetChanged();

        return true;
    }
```

In my project I need to pass this event to the activity because I need to do some other processing too, but to reproduce the crash this may not be necessary. 

I separated in another class the adapter that I use to reproduce the issue: [ImageViewPagerAdapter](https://github.com/luizfp/WCViewPager/blob/master/app/src/main/java/nevet/me/wcviewpagersample/ImageViewPagerAdapter.java)

**Comment by rnevet** [comment]
Sorry, didn't have time to check this yet.

I suspect that there has been a change in the support library that is causing the issue. Probably this change:
https://android.googlesource.com/platform/frameworks/support/+/38cc44cffde90f6fe689b0df6b82f49481a981f7%5E%21/#F2

**Comment by rnevet** [comment]
So I think I solved the issue, but it requires a bit of a change since I can't use the PagerAdapterWrapper anymore. 

Please see the implementation in https://github.com/rnevet/WCViewPager/tree/support24 
Basically your PagerAdapter implementation will need to extend the new class ObjectAtPositionPagerAdapter instead of PagerAdapter.

**Comment by rnevet** [comment]
@luizfp  did you have a chance to test this?

**Comment by luizfp** [comment]
@rnevet Sorry for the delay. I tested and now works fine. No more crashes. Thanks! :+1:
