### ISSUE TITLE
getViewAtPosition(int position) produces index out of bounds exception

### ISSUE THREAD

**Issue by jomapp** [rnevet/WCViewPager#6]
I think there is an error, regarding the position attribute.
Position get's already set correctly so there is no need for "+1".

`// scrolled position is always the left scrolled page
            View leftView = getViewAtPosition(position);
            View rightView = getViewAtPosition(position);`

**Comment by rnevet** [comment]
Both lines cannot refer to the same index, there is no error here.

Check that your implementation of `getObjectAtPosition` returns null in case requested index is out of bounds.

Otherwise please provide a stacktrace.

**Comment by jomapp** [comment]
You're right! Thanks for the explanation.
